# version of docker-compose
version: '3.9'

services:

  postgres:
    image: postgres
    restart: always
    env_file: ./.env
    ports:
      - '${DATABASE_PORT}:5432'
    expose:
      - '${DATABASE_PORT}'
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      PGPASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db:/var/lib/postgres
    stdin_open: true
    tty: true
  api:
    build: .
    ports:
     - "3000:3000"
volumes:
  db:
